export const STATISTIC_STACKED_BAR_BORDER_RADIUS = 6
export const STATISTIC_STACKED_BAR_MAX_BAR_THICKNESS = 42
export const STATISTIC_STACKED_BAR_BORDER_WIDTH = 3
export const STATISTIC_STACKED_BAR_BORDER_COLOR = '#ffffff'
